/*

This file contains HTML code for app of WiFi Message Board

*/

const String page PROGMEM = "<head>"
              
                
                  " <style>"
                    "body{"
                          "background:#130333;"
                      "}"
                      "h1{"
                              "margin-top: -475px;"
                          "color: #FCDB00;"
                          "font-family: impact;"
                          "font-size: 55px;"
                          "text-shadow: -1px -1px 1px #000, 1px 1px 1px #000, -1px 1px 1px #000, 1px -1px 1px #000;"
                          "-webkit-text-fill-color: #e64638;"
                          "-webkit-text-stroke: 1px black;"    
                      "}"
                      "p{"
                      "color: #ecdd30f7;"
                      "font-family: impact;"
                      "font-size: 35px;"
                      "-webkit-text-stroke: 1px black;"
                         
                      "}"
                      "formulario{"
                      "color: #ecdd30f7;"
                      "font-family: impact;"
                      "font-size: 35px;"
                      "-webkit-text-stroke: 1px black;"
                      "}"
                      "input{"
                      "color: #ecdd30f7;"
                      "text-align: center;"
                      "font-family: impact;"
                      "font-size: 35px;"
                      "-webkit-text-stroke: 1px black;"
                      "}"
                      "label{"
                      "color: #ecdd30f7;"
                      "font-family: impact;"
                      "font-size: 35px;"
                      "-webkit-text-stroke: 1px black;"
                        "}"
                        "form{"
                        "}"
                  "</style>"
                  " </head>"
                  " <body>"
                   "<img id='tmm-logo' src='https://i.gifer.com/Ekwj.gif' />"     
                  " <h1>IOT Display de Mensajes</h1>"
                  " <p>Presione Enviar para mandar un mensaje</p>"
                  " <form action='/dataHandler' method='POST'>\r\n"
                  " <label for='message'>Mensaje:</label> <input type='text' name='message' id='message'>""</p>\r\n" 
                  " <input type='submit' id='send' value='Enviar' />\r\n "
                  " </form> \r\n"
                  "</body>";
